### ISSUE TITLE
Way to display decimal only when needed?

### ISSUE THREAD

**Issue by thadrazdow** [thomasa88/ParametricText#67] opened 2024-04-26 17:23 UTC
I have a part that comes in both whole and half sizes (like 5 and 5.5) 
I cant seem to figure out a way to display the value without the decimal when its not needed. 
I also don't want to display it as an expression because I don't want to include the unit 

Would love to have this as a feature or if there's a way to make this work please let me know

Either way thanks everyone involved for this great plugin.

**Comment by thomasa88** [comment] 2024-04-26 18:10
Thank you!

Another user asked me to include the `g` format specifier in the documentation, but it is quite complex to understand, so I have not included it [1]. But you can try it. I'm not at my CAD computer at the moment, but I think it should work well for small numbers (not a lot of digits):

`{myparam:g}`

[1]
From https://docs.python.org/3/library/string.html#formatspec
> General format. For a given precision p >= 1, this rounds the number to p significant digits and then formats the result in either fixed-point format or in scientific notation, depending on its magnitude. A precision of 0 is treated as equivalent to a precision of 1.
> 
> The precise rules are as follows: suppose that the result formatted with presentation type 'e' and precision p-1 would have exponent exp. Then, if m <= exp < p, where m is -4 for floats and -6 for [Decimals](https://docs.python.org/3/library/decimal.html#decimal.Decimal), the number is formatted with presentation type 'f' and precision p-1-exp. Otherwise, the number is formatted with presentation type 'e' and precision p-1. In both cases insignificant trailing zeros are removed from the significand, and the decimal point is also removed if there are no remaining digits following it, unless the '#' option is used.
> 
> With no precision given, uses a precision of 6 significant digits for [float](https://docs.python.org/3/library/functions.html#float). For [Decimal](https://docs.python.org/3/library/decimal.html#decimal.Decimal), the coefficient of the result is formed from the coefficient digits of the value; scientific notation is used for values smaller than 1e-6 in absolute value and values where the place value of the least significant digit is larger than 1, and fixed-point notation is used otherwise.
> 
> Positive and negative infinity, positive and negative zero, and nans, are formatted as inf, -inf, 0, -0 and nan respectively, regardless of the precision.
>

**Comment by thadrazdow** [comment] 2024-04-26 21:37
That worked perfectly thank you! 

I agree the explanation for how g works is very "mathy" and I'm not very well versed in python. 
Maybe including a list of useful format specifiers with simple dumbed down explanations of how they're useful in the context of F360 could be helpful for others.

**Comment by thomasa88** [comment] 2024-04-27 07:49
I had to figure out myself how `g` works :P.

I added some examples with `g` to the `latest` documentation now:
https://parametrictext.readthedocs.io/en/latest/parameters.html#parameter-formatting

I think I have to push a new version for it to appear in the "stable" documentation. 🤔

Duplicate of #43

**Comment by thomasa88** [comment] 2024-04-30 05:45
Release 2.4.1 created, to get the new documentation published as stable: https://parametrictext.readthedocs.io/en/stable/parameters.html

**Closed by thomasa88** 2024-04-30 05:45 UTC
Labels: enhancement
