### ISSUE TITLE
Text update not working when using a python script.

### ISSUE THREAD

**Issue by MuckYu** [thomasa88/ParametricText#57] opened 2023-11-09 15:05 UTC
I am creating several variations of my model with a python script - basically editing the parameters and exporting to .step format.

For some reason the text does not update. When I manually edit the parameter it does update the text just fine.
Is there some function I need to call in my script so that it updates properly?

**Comment by thomasa88** [comment] 2023-11-10 06:00
Hi, ParametricText listens to various events triggered by commands in Fusion. I guess these events don't happen when you modify the parameters using the API.

Please have a look at this comment to see if it helps: https://github.com/thomasa88/ParametricText/issues/54#issuecomment-1605672507

**Comment by thomasa88** [comment] 2023-11-10 06:01
Duplicate of #54

**Closed** 2024-01-17 07:09 UTC
Labels: bug
